version: '3'
services:
  orderservice:
    image: "metro/orderservice"
    ports:
     - "8081:8081"
  supplyservice:
    image: "metro/supplyservice"
    ports:
     - "8083:8083"
  deliveryservice:
    image: "metro/deliveryservice"
    ports:
     - "8082:8082"
    environment:
     ORDERSERVICE_HOST: "http://orderservice:8081"
